### ISSUE TITLE
The performance on your dataset

### ISSUE THREAD

**Issue by zerone-fg** [yichun531/segmentation_mtunet#1]
Hello, I have noticed that you used MT-Unet in your project, I am wondering about the performance of this network,can you share the experiment result with me?thank you.

**Comment by 102278yichun** [comment]
Hi, thanks for noticing my work!

Since this is for my side project in off-work time, I didn't do the complete analysis, sorry!
But in this simple experiment, I found no significant difference in the performance of MT-Unet and UNet, and MT-Unet tended to overfit more faster and severely. 
But I believe there are many ways that can be modified or tuned for improving performance (which I haven't done ˊ_>ˋ).
And another thing is that STAS (lung cancer cell spreading through air spaces (STAS)) images may be much harder contents for segmentation than organ CT (which is the example in MT-Unet paper), therefore in my little simple experiments, I haven't found the power it should have Q_Q

**Comment by zerone-fg** [comment]
Thankyou!!
